hw3 dev

diff --git a/3_psql/Makefile b/3_psql/Makefile
--- a/3_psql/Makefile
+++ b/3_psql/Makefile
@@ -16,5 +16,29 @@ psql-delete:
 	rm -rf ./out/pgdata/* && \
 	echo "files inside pgdata deleted"
 
+migrate-create:
+	@if [ -z "$(name)" ]; then \
+	echo "Missing name, currect example: make migrate-create name=<name>"; \
+	exit 1; \
+	fi; \
+	docker compose run --rm hw3-migrate \
+	create \
+	-ext sql \
+	-dir migrations/ \
+	-seq \
+	$(name)
+
+migrate-up:
+	docker compose run --rm hw3-migrate \
+	-path migrations \
+	-database "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@hw3-psql:5432/${POSTGRES_DB}?sslmode=disable" \
+	up
+
+migrate-down:
+	docker compose run --rm hw3-migrate \
+	-path migrations \
+	-database "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@hw3-psql:5432/${POSTGRES_DB}?sslmode=disable" \
+	down
+
 app-run:
 	go run ./cmd/main.go
